on:
  push:
    branches:
      - main

name: Build, test, release

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  release:
    name: Publish to npm and release on github
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        id: get-version
        with:
          script: |
            // Get the current package.json version
            const { data: content } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'package.json'
            });
            if ('content' in content) {
              return JSON.parse(
                Buffer.from(content.content, 'base64').toString(),
              ).version,
            }
            throw new Error('Could not load main package.json');
      - name: Github Release
        id: release
        uses: whopio/turbo-module@v0.0.3-canary.0
        if: ${{ !startsWith(steps.get-version.outputs.result, '"0.0.0') }}
        with: 
          action: release
          token: ${{ github.token }}
          version: ${{ steps.get-version.outputs.result }}
      - name: Sync auto-release PRs
        uses: whopio/turbo-module@v0.0.3-canary.0
        with: 
          action: sync
          token: ${{ github.token }}
          published: ${{ steps.release.outputs.published }}
