on:
  push:
    branches:
      - tristan/initial

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: get-version
        with:
          script: |
            // Get the current package.json version
            const { data: content } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'package.json'
            });
            if ('content' in content) {
              return JSON.parse(
                Buffer.from(content.content, 'base64').toString(),
              ).version;
            }
            throw new Error('Could not load main package.json');
      - name: Get result
        if: ${{ !startsWith(steps.get-version.outputs.result, "0.0.0") }}
        run: echo "${{ steps.get-version.outputs.result }}"
